name: MinePath
version: '1.1'
main: ollie.minePath.MinePath
api-version: '1.21'
commands:
  minepath:
    description: Controls minepath recorder
    usage: /minepath <start|stop|get|set_delay|reset>
